sudo: false

language: php

cache:
  directories:
    - vendor

php:
  - 5.5
  - 5.6
  - 7

install:
  - composer selfupdate
  - composer install -o -n --prefer-source

before_script:
  - ./yii migrate/up --interactive=0
  
script: 
  - ./vendor/bin/codecept run
